### ISSUE TITLE
モードレスウィンドウにしたい

### ISSUE THREAD

**Issue by KirisameMarisa** [Babumi/DesktopCharacter#23]
設定ウィンドウ、ツール類を開いた時にキャラクターの移動や他のウィンドウを開けないのが不便

**Comment by orekyuu** [comment]
ServiceLocatorのコンフィグスコープで問題が出ないかの確認が必要

**Comment by KirisameMarisa** [comment]
別ウィンドウを開くときのメッセージのModeを変更するだけで対応できるっぽい
<l:TransitionInteractionMessageAction WindowType="{x:Type ToolTimerView:TimerSetting}" Mode="NewOrActive" />

Mode="Modal" -> Mode="NewOrActive"
これでキャラも動かせるし開いたウィンドウも両方動かせるようになる

**Comment by KirisameMarisa** [comment]
機能としてLivetにあるのを使う感じで

とりあえず終わりで
