### ISSUE TITLE
Twitter通知

### ISSUE THREAD

**Issue by orekyuu** [Babumi/DesktopCharacter#8]
# 機能
認証済みのユーザーに関する通知が飛んできた時にキャラクターに通知させる。
通知はアカウント・種類でフィルターをかけられるようにする。

# 対応する通知の種類
- お気に入り追加
- お気に入り削除
- RT
- メンション
- フォローされた
- リムーブされた
- ブロックされた
- ブロックが解除された
- リストに登録された
- 新規ダイレクトメッセージ

**Comment by orekyuu** [comment]
認証ウィンドウの親子付けが終われば完了

**Comment by KirisameMarisa** [comment]
終わったなら閉じちゃっていい？
